drop table ortak.aktarim;
drop table ortak.grpislv;
drop table ortak.grpislvsfh;
drop table ortak.grpkisi;
drop table ortak.grpkisisfh;
drop table ortak.grptnm;
drop table ortak.kisirsm;
drop table ortak.kisitnm;
drop table ortak.kytnu;
drop table ortak.ortkod;
drop table ortak.prjgrssfh;
drop table ortak.prjtnm;
drop table ortak.prldgssfh;
drop schema ortak restrict;